# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.0.0.$(Date:yyyyMMdd)$(Rev:rr)

trigger:
- master

variables:
  buildConfiguration: 'Release'


steps:
# - script: echo $(MyRunNumber) # display MyRunNumber
# - script: echo $(Build.BuildNumber) #display Run Number

- script: dotnet restore 
  displayName: 'restore...'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ContainerAPI'
    publishLocation: 'Container'
    




  
