# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.0.0.$(Date:yyyyMMdd)$(Rev:rr)

trigger:
- master

variables:
  buildConfiguration: 'Release'


steps:

- task: DotNetCoreCLI@2 
  displayName: Install NBGV tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
 
- script: nbgv cloud
  displayName: Set Version

- script: echo 'My run number ' $(MyRunNumber) # display MyRunNumber
- script: echo 'Build number ' $(Build.BuildNumber) #display Run Number

- script: dotnet restore 
  displayName: 'restore...'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ContainerAPI'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'CNeff-Primary(2d918367-9b82-47de-802a-d8275e07edbf)'
    appType: 'webApp'
    WebAppName: 'sample-devops'
    packageForLinux: '$(Build.ArtifactStagingDirectory)'
    




  
